### ISSUE TITLE
Operators are highlighted with a white background on dark themes

### ISSUE THREAD

**Issue by Demdillypickles** [altudev/Brism#2]
The prism.css file provided by your project has the code below:

```CSS
.language-css .token.string,.style .token.string,.token.entity,.token.operator,.token.url {
    color: #9a6e3a;
    background: hsla(0,0%,100%,.5)
}
```

I do not see this style in the original prism.css from the PrismJS project.

This small bit of code is causing operators to be highlighted with a white background, even in dark themes. What was the reason for including this? Unless I am missing something,  I think it should just be removed entirely. This small issue is making dark themes "unusable" with your component.

Screenshot example of operators being highlighted with a transparent white background. Makes dark themes look bad.

![Image](https://github.com/user-attachments/assets/76812cc5-8918-48f0-a943-271f2f3b1c4c)
